name: Coveralls
on: [push, pull_request]

jobs:
  cov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo pip install --upgrade cpp-coveralls;
      - run: |
          git clone https://github.com/ryuichis/oclint
          cd oclint
          git checkout use-system-llvm
          cd oclint-scripts
          ./gh-actions test core
          cd ..
          coveralls --include oclint-core/ --exclude oclint-core/test;
