name: Coveralls
on: [push, pull_request]

jobs:
  cov-on-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          git clone https://github.com/ryuichis/oclint
          cd oclint
          git checkout use-system-llvm
      - run: |
          cd oclint/oclint-scripts
          ./gh-actions test metrics
          cd ..
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          TRAVIS_JOB_ID: ${{ github.run_number }}
        run: |
          sudo pip install --upgrade cpp-coveralls
          cd oclint
          echo -e "service_name: gh-actions\n" > .coveralls.yml
          coveralls --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test
  cov-on-mac:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer
          git clone https://github.com/ryuichis/oclint
          cd oclint
          git checkout use-system-llvm
      - run: |
          cd oclint/oclint-scripts
          ./gh-actions test metrics
          cd ..
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          TRAVIS_JOB_ID: ${{ github.run_number }}
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv;
          eval "$(pyenv init -)";
          pyenv install 3.8.2;
          pyenv global 3.8.2;
          pyenv rehash;
          pip install cpp-coveralls;
          pyenv rehash;
          cd oclint
          echo -e "service_name: gh-actions\n" > .coveralls.yml
          coveralls --gcov $(pwd)/build/llvm-install/bin/llvm-cov --gcov-options gcov --include oclint-core/ --exclude oclint-core/test
